### ISSUE TITLE
No issues

### ISSUE THREAD

**Issue by Gulfbreeze** [daleyjem/ustvnow-firetv#3]
Are there any plans on adding access to the DVR feature provided by USTVNow?

**Comment by daleyjem** [comment]
Since I've "re-attached" the cable cord, I've not been using USTVNow. Unless there are contributions from other developers, certain features are certain to either never occur, or at a time distant in the future.

At this time, I can only recommend strongly encouraging USTVNow to building apps for display on televisions, through services like Amazon FireTV apps.
